server {

        server_name sipeka.atmaku.com www.sipeka.atmaku.com;

        location ~/api/*  {
                proxy_redirect http://localhost:8080/ https://$server_name/;
                proxy_pass http://localhost:8080;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';

               include proxy_params;
        }

        location ~/socket.io/*  {
                proxy_redirect http://localhost:8080/ https://$server_name/;
                proxy_pass http://localhost:8080;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';

               include proxy_params;
        }

        location ~ ^.+\..+$ {
                proxy_redirect http://localhost:8080/ https://$server_name/;
                proxy_pass http://localhost:8080;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';

               include proxy_params;
        }

        location / {
                try_files $uri $uri/ /index.html;
        }
}


